name: Build and test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build SuckIT
      run: |
          rustup component add rustfmt
          cargo fmt -- --check || (echo "Please reformat your code with 'cargo
          fmt' (version $(cargo fmt --version))"; false)

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build SuckIT
      run: |
          cargo build

  tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: |
          cargo test
